import type { ConfigSchema } from "../../contracts/plugin";

export const LLM_CORE_SCHEMA: ConfigSchema = [
  {
    key: "communicator",
    label: "AI service",
    type: "string",
    placeholder: "(first chat-capable service)",
    help: "Name of the configured AI service this agent talks to. Leave blank to use the first chat-capable service.",
  },
  {
    key: "temperature",
    label: "Temperature",
    type: "number",
    min: 0,
    max: 2,
    step: 0.1,
    placeholder: "provider default",
    help: "Sampling temperature. Leave blank to use the provider default.",
  },
  {
    key: "maxTokens",
    label: "Max output tokens",
    type: "number",
    min: 1,
    step: 1,
    placeholder: "provider default",
    help: "Upper bound on the reply length. Leave blank for the provider default.",
  },
  {
    key: "contextLimitTokens",
    label: "Context window override",
    type: "number",
    min: 1,
    step: 1,
    placeholder: "(use the service's own context length)",
    help: "Override the model's context-window size (in tokens) used for the overflow budget. Leave blank to use the AI service's declared context length.",
  },
  {
    key: "charsPerToken",
    label: "Characters per token",
    type: "number",
    min: 1,
    step: 0.1,
    placeholder: "4",
    help: "Rough characters-per-token ratio used to estimate the prompt size. Default 4.",
  },
  {
    key: "maxReduceRounds",
    label: "Max shrink rounds",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "3",
    help: "How many times to ask message-block plugins to shrink the prompt when it overflows the context budget, per frame. Set 0 to disable overflow handling. Default 3.",
  },
  {
    key: "safetyTokens",
    label: "Safety margin tokens",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "200",
    help: "Tokens held back from the context window as headroom when computing the overflow budget. Default 200.",
  },
  {
    key: "retryOnContextError",
    label: "Retry on context-overflow error",
    type: "boolean",
    help: "When the AI service rejects a request because the prompt is too long, shrink the prompt and retry (up to the max shrink rounds) instead of failing. Catches overflows the size estimate missed. Default on.",
  },
  {
    key: "contextErrorPatterns",
    label: "Context-overflow error patterns",
    type: "list",
    placeholder: "context_length_exceeded, prompt is too long",
    help: "Provider error text (matched case-insensitively, each entry tried as a regular expression) that marks a rejection as a context overflow eligible for the shrink-and-retry above. Leave blank to use the built-in defaults.",
  },
];
